/**
 * GenHub
 * GenHub api
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Role { 
    description?: string;
    id?: number;
    name?: string;
    status?: number;
}
