export * from './status.service';
import { StatusService } from './status.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './channel.admin.service';
import { ChannelAdminService } from './channel.admin.service';
// export * from './commentController.service';
// import { CommentControllerService } from './commentController.service';
// export * from './favorController.service';
// import { FavorControllerService } from './favorController.service';
// export * from './optionsController.service';
// import { OptionsControllerService } from './optionsController.service';
// export * from './postController.service';
// import { PostControllerService } from './postController.service';
// export * from './roleController.service';
// import { RoleControllerService } from './roleController.service';
// export * from './uploadController.service';
// import { UploadControllerService } from './uploadController.service';
// export * from './userController.service';
// import { UserControllerService } from './userController.service';
export const APIS = [StatusService, UserService, ChannelAdminService];
