// /**
//  * GenHub
//  * GenHub api
//  *
//  * OpenAPI spec version: 1.0
//  * 
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  * Do not edit the class manually.
//  */
// /* tslint:disable:no-unused-variable member-ordering */

// import { Inject, Injectable, Optional }                      from '@angular/core';
// import { HttpClient, HttpHeaders, HttpParams,
//          HttpResponse, HttpEvent }                           from '@angular/common/http';
// import { CustomHttpUrlEncodingCodec }                        from '../encoder';

// import { Observable }                                        from 'rxjs/Observable';

// import { PagePostVO } from '../model/pagePostVO';
// import { PostVO } from '../model/postVO';
// import { Resultobject } from '../model/resultobject';

// import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
// import { Configuration }                                     from '../configuration';


// @Injectable()
// export class PostControllerService {

//     protected basePath = 'https://localhost:8080/socialty/api/v1';
//     public defaultHeaders = new HttpHeaders();
//     public configuration = new Configuration();

//     constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
//         if (basePath) {
//             this.basePath = basePath;
//         }
//         if (configuration) {
//             this.configuration = configuration;
//             this.basePath = basePath || configuration.basePath || this.basePath;
//         }
//     }

//     /**
//      * @param consumes string[] mime-types
//      * @return true: consumes contains 'multipart/form-data', false: otherwise
//      */
//     private canConsumeForm(consumes: string[]): boolean {
//         const form = 'multipart/form-data';
//         for (const consume of consumes) {
//             if (form === consume) {
//                 return true;
//             }
//         }
//         return false;
//     }


//     /**
//      * delete
//      * 
//      * @param id id
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public deleteUsingDELETE3(id: number, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public deleteUsingDELETE3(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public deleteUsingDELETE3(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public deleteUsingDELETE3(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling deleteUsingDELETE3.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.delete<Resultobject>(`${this.basePath}/user/post/delete/${encodeURIComponent(String(id))}`,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * delete
//      * 
//      * @param id id
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public deleteUsingDELETE4(id: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public deleteUsingDELETE4(id: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public deleteUsingDELETE4(id: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public deleteUsingDELETE4(id: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling deleteUsingDELETE4.');
//         }

//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (id) {
//             id.forEach((element) => {
//                 queryParameters = queryParameters.append('id', <any>element);
//             })
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.delete<Resultobject>(`${this.basePath}/admin/post/delete`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * featured
//      * 
//      * @param featured featured
//      * @param id id
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public featuredUsingPUT(featured: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public featuredUsingPUT(featured: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public featuredUsingPUT(featured: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public featuredUsingPUT(featured: number, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (featured === null || featured === undefined) {
//             throw new Error('Required parameter featured was null or undefined when calling featuredUsingPUT.');
//         }

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling featuredUsingPUT.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];

//         return this.httpClient.put<Resultobject>(`${this.basePath}/admin/post/featured/${encodeURIComponent(String(id))}/${encodeURIComponent(String(featured))}`,
//             null,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * list
//      * 
//      * @param channelId channelId
//      * @param page page
//      * @param size size
//      * @param title title
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public listUsingGET2(channelId?: number, page?: number, size?: number, title?: string, observe?: 'body', reportProgress?: boolean): Observable<PagePostVO>;
//     public listUsingGET2(channelId?: number, page?: number, size?: number, title?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PagePostVO>>;
//     public listUsingGET2(channelId?: number, page?: number, size?: number, title?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PagePostVO>>;
//     public listUsingGET2(channelId?: number, page?: number, size?: number, title?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (channelId !== undefined && channelId !== null) {
//             queryParameters = queryParameters.set('channelId', <any>channelId);
//         }
//         if (page !== undefined && page !== null) {
//             queryParameters = queryParameters.set('page', <any>page);
//         }
//         if (size !== undefined && size !== null) {
//             queryParameters = queryParameters.set('size', <any>size);
//         }
//         if (title !== undefined && title !== null) {
//             queryParameters = queryParameters.set('title', <any>title);
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<PagePostVO>(`${this.basePath}/admin/post/list`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * post
//      * 
//      * @param post post
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public postUsingPOST1(post: PostVO, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public postUsingPOST1(post: PostVO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public postUsingPOST1(post: PostVO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public postUsingPOST1(post: PostVO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (post === null || post === undefined) {
//             throw new Error('Required parameter post was null or undefined when calling postUsingPOST1.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];
//         const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
//         if (httpContentTypeSelected != undefined) {
//             headers = headers.set('Content-Type', httpContentTypeSelected);
//         }

//         return this.httpClient.post<Resultobject>(`${this.basePath}/user/post/submit`,
//             post,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * subUpdate
//      * 
//      * @param post post
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public subUpdateUsingPOST(post: PostVO, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public subUpdateUsingPOST(post: PostVO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public subUpdateUsingPOST(post: PostVO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public subUpdateUsingPOST(post: PostVO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (post === null || post === undefined) {
//             throw new Error('Required parameter post was null or undefined when calling subUpdateUsingPOST.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];
//         const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
//         if (httpContentTypeSelected != undefined) {
//             headers = headers.set('Content-Type', httpContentTypeSelected);
//         }

//         return this.httpClient.post<Resultobject>(`${this.basePath}/admin/post/update`,
//             post,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * toUpdate
//      * 
//      * @param id id
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public toUpdateUsingGET(id?: number, observe?: 'body', reportProgress?: boolean): Observable<PostVO>;
//     public toUpdateUsingGET(id?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PostVO>>;
//     public toUpdateUsingGET(id?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PostVO>>;
//     public toUpdateUsingGET(id?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


//         let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
//         if (id !== undefined && id !== null) {
//             queryParameters = queryParameters.set('id', <any>id);
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<PostVO>(`${this.basePath}/admin/post/view`,
//             {
//                 params: queryParameters,
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * view
//      * 
//      * @param id id
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public viewUsingGET2(id: number, observe?: 'body', reportProgress?: boolean): Observable<PostVO>;
//     public viewUsingGET2(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PostVO>>;
//     public viewUsingGET2(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PostVO>>;
//     public viewUsingGET2(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling viewUsingGET2.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//         ];

//         return this.httpClient.get<PostVO>(`${this.basePath}/user/post/editing/${encodeURIComponent(String(id))}`,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

//     /**
//      * weight
//      * 
//      * @param id id
//      * @param weight weight
//      * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
//      * @param reportProgress flag to report request and response progress.
//      */
//     public weightUsingPUT1(id: number, weight: number, observe?: 'body', reportProgress?: boolean): Observable<Resultobject>;
//     public weightUsingPUT1(id: number, weight: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resultobject>>;
//     public weightUsingPUT1(id: number, weight: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resultobject>>;
//     public weightUsingPUT1(id: number, weight: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

//         if (id === null || id === undefined) {
//             throw new Error('Required parameter id was null or undefined when calling weightUsingPUT1.');
//         }

//         if (weight === null || weight === undefined) {
//             throw new Error('Required parameter weight was null or undefined when calling weightUsingPUT1.');
//         }

//         let headers = this.defaultHeaders;

//         // authentication (JWT) required
//         if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
//             headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
//         }

//         // to determine the Accept header
//         let httpHeaderAccepts: string[] = [
//             '*/*'
//         ];
//         const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
//         if (httpHeaderAcceptSelected != undefined) {
//             headers = headers.set('Accept', httpHeaderAcceptSelected);
//         }

//         // to determine the Content-Type header
//         const consumes: string[] = [
//             'application/json'
//         ];

//         return this.httpClient.put<Resultobject>(`${this.basePath}/admin/post/weight/${encodeURIComponent(String(id))}`,
//             null,
//             {
//                 withCredentials: this.configuration.withCredentials,
//                 headers: headers,
//                 observe: observe,
//                 reportProgress: reportProgress
//             }
//         );
//     }

// }
